version: '3.1'
# name = docker-compose -f docker-compose.mont-db.yaml up

services:

  postgresql:
    image: eduardolr/postgres:13.4-buster
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
