version: '3.1'

services:

  nginx-server:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./Front/nginx.conf:/etc/nginx/nginx.conf 
      - ./Front/project/build:/usr/share/nginx/html
